[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Netlify Identity 配置
[context.production.environment]
  NODE_ENV = "production"

# 重定向规则 - 处理 SPA 路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Identity 相关重定向
[[redirects]]
  from = "/.netlify/identity"
  to = "/.netlify/identity"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/index.html"
  status = 200
